-- PRODUCT
-- PRODUCT (Postgres)
create table if not exists product (
  id bigint generated by default as identity primary key,
  category varchar(255) not null,
  description text not null,
  featured boolean not null,
  material_cost numeric(10,2) not null,
  name varchar(255) not null,
  new_arrival boolean not null,
  picture_type varchar(255),
  picture_version bigint not null,
  price numeric(19,2) not null,
  product_picture_file bytea,
  quantity integer not null,
  sold_out boolean not null
);

-- ORDERS
create table if not exists orders (
  order_id bigint generated by default as identity primary key,
  carrier varchar(255),
  created_at timestamp not null,
  delivered_at timestamp,
  discount_total numeric(10,2) not null,
  follow_up_notes TEXT,
  follow_up_resolved_at timestamp,
  label_created boolean not null,
  needs_follow_up boolean not null,
  order_email varchar(255) not null,
  order_name varchar(255) not null,
  order_status varchar(255) not null,
  order_total numeric(10,2) not null,
  shipped_at timestamp,
  shipping_address1 varchar(255),
  shipping_address2 varchar(255),
  shipping_city varchar(255),
  shipping_state varchar(255),
  shipping_total numeric(10,2) not null,
  shipping_zip varchar(255),
  subtotal numeric(10,2) not null,
  tax_total numeric(10,2) not null,
  tracking_number varchar(255)
);

-- ORDER_ITEMS
create table if not exists order_items (
  id bigint generated by default as identity primary key,
  material_cost_at_sale numeric(10,2) not null,
  product_id bigint not null,
  product_name varchar(255) not null,
  quantity integer not null,
  unit_price numeric(10,2) not null,
  order_id bigint not null,
  constraint FK_order_items_orders
    foreign key (order_id) references orders (order_id)
);